# -*- coding: utf-8 -*-
"""
Результат ручной визуальной классификации 185 страниц (168 страниц-сканов без
текстового слоя + 17 титульных страниц из editorial-issues.pdf-stage.json),
выполненной по контактным листам workspace/visual-renders/contact-sheets/.

Формат записи: page: (page_type, [features], confidence, review_required, [notes])

page_type — один из словаря типов задания (cover, title_page, official_message,
contents, section_opener, person_opener, biography_text, biography_with_photo,
portrait, photo_collage, handwritten_letter, typed_letter, child_drawing,
quotation, document_scan, mixed_material, closing_page, unknown).

Не выполнялось: распознавание лиц, установление авторства по сходству.
"""

VISUAL = {
    # --- Sheet 1: pages 13-39 ---
    13: ("photo_collage", ["has_multiple_photos", "has_portrait", "has_child_art"], 0.85, False, []),
    14: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    15: ("person_opener", ["has_coat_of_arms", "has_map"], 0.9, True, ["editorial_issue:eq-008 (имена авторов смешанным регистром)"]),
    16: ("photo_collage", ["has_multiple_photos", "has_child_art", "has_medal_or_award"], 0.8, False, []),
    17: ("mixed_material", ["has_handwriting", "has_child_art", "has_family_photo"], 0.75, False, []),
    18: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    20: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    21: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    22: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    23: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    25: ("mixed_material", ["has_handwriting", "has_family_photo"], 0.75, False, []),
    27: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    28: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    30: ("photo_collage", ["has_family_photo", "has_medal_or_award"], 0.85, False, []),
    31: ("mixed_material", ["has_handwriting", "has_official_symbols"], 0.7, False, []),
    33: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    34: ("mixed_material", ["has_family_photo", "has_handwriting"], 0.75, False, []),
    36: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    37: ("mixed_material", ["has_family_photo", "has_handwriting"], 0.75, False, []),
    39: ("photo_collage", ["has_family_photo"], 0.8, False, []),

    # --- Sheet 2: pages 40-64 ---
    40: ("mixed_material", ["has_family_photo", "has_handwriting"], 0.8, False, []),
    42: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    43: ("mixed_material", ["has_handwriting", "has_family_photo", "has_low_readability"], 0.6, True, ["тёмные/малоконтрастные фото"]),
    45: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    46: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    47: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    49: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    50: ("mixed_material", ["has_family_photo", "has_handwriting"], 0.75, False, []),
    51: ("person_opener", ["has_medal_or_award", "has_coat_of_arms", "has_map"], 0.9, True,
         ["editorial_issue:eq-006 — на самом рендере слайда видна ТОЛЬКО усечённая надпись "
          "«г.Санкт- Петербур»; полный вариант «г. Санкт-Петербург» в текстовом слое не виден "
          "на изображении -> вероятно скрытый/второй текстбокс"]),
    52: ("photo_collage", ["has_family_photo", "has_medal_or_award", "has_multiple_photos"], 0.85, False, []),
    53: ("photo_collage", ["has_medal_or_award", "has_multiple_photos"], 0.85, False, []),
    54: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    56: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    57: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    58: ("child_drawing", ["has_child_art"], 0.9, False, []),
    59: ("handwritten_letter", ["has_handwriting"], 0.8, False, []),
    60: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    62: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    63: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    64: ("person_opener", ["has_coat_of_arms", "has_map"], 0.9, True,
         ["editorial_issue:eq-003 — блок героя (hero-016) состоит ТОЛЬКО из этой титульной "
          "страницы, материалов нет (следующая страница — уже титул hero-017)"]),

    # --- Sheet 3: pages 65-93 ---
    65: ("person_opener", ["has_coat_of_arms", "has_map"], 0.9, True,
         ["editorial_issue:eq-003 — визуально идентична p.064 (тот же текст, герб, карта); "
          "visually_confirmed_duplicate"]),
    66: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    67: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    69: ("handwritten_letter", ["has_handwriting"], 0.85, False, []),
    71: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    72: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    74: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    75: ("handwritten_letter", ["has_handwriting"], 0.85, False, []),
    77: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    78: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    80: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    81: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    83: ("portrait", ["has_portrait"], 0.7, False, ["одиночное фото, не коллаж"]),
    84: ("mixed_material", ["has_handwriting", "has_family_photo"], 0.75, False, []),
    86: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    87: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    89: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    90: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    92: ("mixed_material", ["has_family_photo", "has_child_art"], 0.7, False, []),
    93: ("portrait", ["has_family_photo"], 0.75, False, ["одиночное фото: девочка с портретом героя"]),

    # --- Sheet 4: pages 94-120 ---
    94: ("handwritten_letter", ["has_handwriting"], 0.85, False, []),
    96: ("photo_collage", ["has_family_photo", "has_official_symbols"], 0.75, False, ["мемориальный баннер/билборд"]),
    97: ("handwritten_letter", ["has_handwriting"], 0.7, False, ["короткая записка"]),
    99: ("photo_collage", ["has_medal_or_award", "has_family_photo", "has_multiple_photos"], 0.85, False, []),
    100: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    101: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    102: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    104: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    105: ("mixed_material", ["has_family_photo", "has_handwriting"], 0.75, False, []),
    106: ("person_opener", ["has_medal_or_award"], 0.9, True,
          ["editorial_issue:eq-001 (1/7) — титул содержит ТОЛЬКО значок ордена и текст на "
           "белом фоне; ОТСУТСТВУЮТ герб региона и карта РФ, присутствующие на всех остальных "
           "76 титулах героев -> вероятно незавершённый/шаблонный слайд", "possible_placeholder"]),
    107: ("photo_collage", ["has_medal_or_award", "has_family_photo", "has_multiple_photos"], 0.85, False, []),
    108: ("handwritten_letter", ["has_handwriting"], 0.75, False, ["короткая записка"]),
    110: ("photo_collage", ["has_multiple_photos", "has_medal_or_award"], 0.8, False, []),
    111: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    113: ("photo_collage", ["has_medal_or_award", "has_family_photo", "has_multiple_photos"], 0.85, False, []),
    114: ("handwritten_letter", ["has_handwriting"], 0.75, False, []),
    116: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    117: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    119: ("photo_collage", ["has_family_photo"], 0.8, False, []),
    120: ("handwritten_letter", ["has_handwriting"], 0.75, False, []),

    # --- Sheet 5: pages 122-149 ---
    122: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    123: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    125: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    126: ("mixed_material", ["has_child_art", "has_handwriting", "has_official_symbols"], 0.8, False, []),
    128: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    129: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    131: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    132: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    134: ("photo_collage", ["has_medal_or_award", "has_family_photo", "has_multiple_photos"], 0.85, False, []),
    135: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    137: ("photo_collage", ["has_family_photo"], 0.8, False, []),
    138: ("document_scan", ["has_handwriting", "has_portrait", "has_low_readability", "has_caption"], 0.5, True,
          ["необычная композиция, похоже на мемориальную карточку/буклет"]),
    139: ("person_opener", ["has_medal_or_award"], 0.9, True,
          ["editorial_issue:eq-001 (2/7) — тот же дефект, что и p.106: нет герба и карты", "possible_placeholder"]),
    140: ("photo_collage", ["has_family_photo", "has_official_symbols"], 0.8, False, []),
    141: ("handwritten_letter", ["has_handwriting"], 0.75, False, []),
    143: ("photo_collage", ["has_family_photo"], 0.8, False, []),
    144: ("handwritten_letter", ["has_handwriting", "has_low_readability"], 0.6, True, []),
    146: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    147: ("handwritten_letter", ["has_handwriting"], 0.8, False, []),
    149: ("photo_collage", ["has_family_photo"], 0.8, False, []),

    # --- Sheet 6: pages 150-175 ---
    150: ("typed_letter", [], 0.55, True, ["текст очень ровный, похож на печатный/перепечатанный, не на почерк ребёнка"]),
    152: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    153: ("typed_letter", [], 0.55, True, ["два коротких печатных блока текста с подписями"]),
    155: ("photo_collage", ["has_portrait", "has_family_photo"], 0.8, False, []),
    156: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    158: ("photo_collage", ["has_multiple_photos"], 0.75, False, []),
    159: ("photo_collage", ["has_medal_or_award", "has_multiple_photos"], 0.85, False, []),
    160: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    161: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    163: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    164: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    166: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    167: ("handwritten_letter", ["has_handwriting", "has_low_readability"], 0.6, True, []),
    169: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    170: ("photo_collage", ["has_family_photo", "has_official_symbols"], 0.75, False, []),
    171: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    172: ("person_opener", ["has_coat_of_arms", "has_map"], 0.9, True, ["editorial_issue:eq-004 (A)"]),
    173: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    174: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    175: ("person_opener", ["has_coat_of_arms", "has_map"], 0.9, True,
          ["editorial_issue:eq-004 (B) — визуально идентична p.172 (тот же текст, герб, карта); "
           "visually_confirmed_duplicate; между p.172 и p.175 — свой полноценный комплект "
           "материалов (фотоколлаж+письмо) у каждого титула"]),

    # --- Sheet 7: pages 176-197 ---
    176: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    177: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    178: ("person_opener", ["has_medal_or_award"], 0.9, True,
          ["editorial_issue:eq-001 (3/7) — тот же дефект: нет герба и карты", "possible_placeholder"]),
    179: ("photo_collage", ["has_family_photo"], 0.8, False, []),
    180: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    181: ("person_opener", ["has_medal_or_award", "has_coat_of_arms", "has_map"], 0.9, True,
          ["editorial_issue:eq-002 — титул ПОЛНЫЙ (герб Волгоградской обл., карта); в отличие "
           "от 7 неполных титулов с теми же именами детей, этот титул структурно корректен"]),
    182: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    183: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    184: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    185: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    186: ("person_opener", ["has_medal_or_award"], 0.9, True,
          ["editorial_issue:eq-001 (4/7) — тот же дефект: нет герба и карты", "possible_placeholder"]),
    187: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    188: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    189: ("person_opener", ["has_medal_or_award"], 0.9, True,
          ["editorial_issue:eq-001 (5/7) — тот же дефект: нет герба и карты", "possible_placeholder"]),
    190: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    191: ("mixed_material", ["has_handwriting", "has_child_art"], 0.7, False, ["заголовок «ГЕРОЙ!» + текст + рисунок-звезда"]),
    193: ("photo_collage", ["has_medal_or_award", "has_family_photo", "has_multiple_photos"], 0.85, False, []),
    194: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    195: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    197: ("photo_collage", ["has_family_photo"], 0.8, False, []),

    # --- Sheet 8: pages 199-221 ---
    199: ("photo_collage", ["has_family_photo"], 0.8, False, []),
    200: ("handwritten_letter", ["has_handwriting"], 0.85, False, []),
    202: ("photo_collage", ["has_family_photo", "has_official_symbols"], 0.8, False, []),
    203: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    204: ("person_opener", ["has_coat_of_arms", "has_map"], 0.9, True,
          ["editorial_issue:eq-007 — герб г. Москвы и карта присутствуют; повтор "
           "«г. Москва г. Москва» выглядит структурным (регион=город для городов "
           "федерального значения), та же структура у Санкт-Петербурга/Севастополя"]),
    205: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    206: ("handwritten_letter", ["has_handwriting"], 0.85, False, []),
    207: ("person_opener", ["has_coat_of_arms", "has_map"], 0.9, True,
          ["editorial_issue:eq-005 — «АМИР????» отображается именно так на самом рендере "
           "слайда (не только в текстовом слое) -> вероятно нечитаемый спецсимвол/эмодзи "
           "прямо в исходном тексте PowerPoint"]),
    208: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    209: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    211: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    212: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    213: ("person_opener", ["has_medal_or_award"], 0.9, True,
          ["editorial_issue:eq-001 (6/7) — тот же дефект: нет герба и карты", "possible_placeholder"]),
    214: ("photo_collage", ["has_family_photo", "has_multiple_photos"], 0.85, False, []),
    215: ("handwritten_letter", ["has_handwriting"], 0.8, False, []),
    216: ("person_opener", ["has_medal_or_award"], 0.9, True,
          ["editorial_issue:eq-001 (7/7) — тот же дефект: нет герба и карты", "possible_placeholder"]),
    217: ("photo_collage", ["has_family_photo"], 0.8, False, []),
    219: ("photo_collage", ["has_family_photo"], 0.8, False, []),
    220: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    221: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),

    # --- Sheet 9: pages 222-248 ---
    222: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    224: ("photo_collage", ["has_family_photo", "has_official_symbols"], 0.75, False, ["мемориальная табличка с цветами"]),
    225: ("quotation", [], 0.7, False, ["печатный текст, похожий на стихотворение/посвящение"]),
    227: ("photo_collage", ["has_medal_or_award", "has_family_photo", "has_official_symbols"], 0.8, False, []),
    228: ("photo_collage", ["has_medal_or_award", "has_portrait"], 0.8, False, []),
    229: ("handwritten_letter", ["has_handwriting"], 0.85, False, []),
    231: ("photo_collage", ["has_family_photo", "has_multiple_photos", "has_official_symbols"], 0.8, False, []),
    232: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    233: ("mixed_material", ["has_handwriting", "has_official_symbols", "has_family_photo"], 0.7, False, ["фото церемонии/выпуска"]),
    234: ("person_opener", ["has_coat_of_arms", "has_map"], 0.9, True,
          ["editorial_issue:eq-006 (2-я страница той же проблемы) — на рендере слайда "
           "видна ТОЛЬКО усечённая надпись «г.Санкт- Петербур», как и на p.051"]),
    235: ("photo_collage", ["has_family_photo", "has_official_symbols"], 0.8, False, []),
    236: ("handwritten_letter", ["has_handwriting"], 0.75, False, []),
    238: ("photo_collage", ["has_family_photo", "has_official_symbols"], 0.8, False, ["мемориал «ПОМНИ ВОЙНУ»"]),
    239: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    241: ("mixed_material", ["has_official_symbols", "has_family_photo", "has_caption"], 0.7, False, ["мемориальная табличка с ФИО и датами + семейное фото"]),
    242: ("mixed_material", ["has_medal_or_award", "has_handwriting", "has_family_photo"], 0.75, False, []),
    244: ("photo_collage", ["has_family_photo"], 0.85, False, []),
    245: ("handwritten_letter", ["has_handwriting"], 0.8, False, []),
    247: ("mixed_material", ["has_official_symbols", "has_caption", "has_family_photo"], 0.7, False, ["мемориальная плита с ФИО и датами + групповое фото"]),
    248: ("photo_collage", ["has_family_photo", "has_official_symbols"], 0.8, False, []),

    # --- Sheet 10: pages 249-255 ---
    249: ("handwritten_letter", ["has_handwriting"], 0.9, False, []),
    251: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    252: ("handwritten_letter", ["has_handwriting"], 0.75, False, []),
    254: ("photo_collage", ["has_medal_or_award", "has_family_photo"], 0.85, False, []),
    255: ("handwritten_letter", ["has_handwriting"], 0.85, False, ["последняя страница книги (255/255)"]),
}
